---
services:
  ldap_sync:
    volumes:
      - ./itest/config.toml:/config.toml:ro

  vaultwarden: {}

  ldap:
    command: ["--copy-service"]
    volumes:
      - ./itest/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
